[build]
  publish = "public/IRIS-IRIR"
  functions = "netlify/functions"
  command = "fc-list && npm install"
[build.environment]
  NODE_VERSION = "20"
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
[functions]
  node_bundler = "zisi"
  external_node_modules = ["sharp"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
